services:
  - type: web
    name: my-api-server
    env: node
    plan: free
    region: singapore
    buildCommand: "npm install"
    startCommand: "node backend/server.js"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22.0.0
